### ISSUE TITLE
Add the following details in their respective tabs

### ISSUE THREAD

**Issue by swengr-janan** [mgguild/gamevault-frontend#153]
![image](https://user-images.githubusercontent.com/61826995/156717350-041fb194-2028-46ed-97e5-9ce7eed288ca.png)

**Token Sale:** 

- Token Name: 
- Ticker:
- Sale Price:
- Buying Coin:
- Funds to be raised:
- Token Distribution:

**Schedule:**

- Sale Start Time:
- Sale End Time:

**Allocation:**

- Wallet Address: _(user's wallet address)_
- Allocation: _(user's wallet allocation)_
- Distribution Mode:

**Comment by kojiadrianojr** [comment]
@swengr-janan yung sa Token Sale, papalitan or i-dadagdag ?

**Comment by swengr-janan** [comment]
Tanggalin mo na lang @kojiadrianojr yung mga dating nadoon tapos dagdag mo yung mga anjan sa list sa taas

**Comment by swengr-janan** [comment]
si Sale Price lang naman yung matitira
