### ISSUE TITLE
Update website title

### ISSUE THREAD

**Issue by swengr-janan** [mgguild/gamevault-frontend#155]
![image](https://user-images.githubusercontent.com/61826995/156718632-3f4ddde7-1ab6-4396-81f1-e31bec034905.png)

Change to -> **MGG Launchpad - _Project Name_**

**Comment by kojiadrianojr** [comment]
Saang part nga to @swengr-janan ? paki screenshot ng buong page

**Comment by swengr-janan** [comment]
Ini @kojiadrianojr 

![image](https://user-images.githubusercontent.com/61826995/156993719-ea6875af-7d5d-46ad-9219-ea1af9e8b02a.png)

**Comment by kojiadrianojr** [comment]
copy copy
