### ISSUE TITLE
To check during Round 1 IGO 

### ISSUE THREAD

**Issue by swengr-janan** [mgguild/gamevault-frontend#181]
**_Card_**

- [ ] Check if the status is ongoing
- [ ] Check countdown timer if correct
- [ ] Check total raised if correct (total raised is the amount of WZRD token sold in BUSD)
- [ ] Check if WZRD for sale if 500,000 WZRD
- [ ] Check if buying coin is BUSD
- [ ] Check if distribution type is correct. (In Wizardia it is _Vesting_)

**_Individual Project Page_**

- [ ] Check status if ongoing
- [ ] Check social media links if correct
- [ ] Check countdown timer if correct
- [ ] Check percentage of tokens sold ( percentage = token sold / token for sale)
- [ ] Check total raised if correct (total raised is the amount of WZRD token sold in BUSD)
- [ ] Check token price. ( 1 WZRD = **0.12 BUSD**)
- [ ] Check tokens sold if correct
- [ ] User should not be able to purchase more than their max allocation.
- [ ] My allocation shows the number of tokens bought by the user
- [ ] If users already bought all of their allocations, the purchase button should be disabled
- [ ] Sold Out button should appear if there are no more tokens available.
- [ ] Non whitelisted addresses should not be able to participate

**_Purchase Modal_**
- [ ] Check if Price per BUSD is correct
- [ ] When clicking Max button, it should input the user's remaining allocation
- [ ] My allocation shows the number of tokens bought by the user
- [ ] After swapping/buying, tokens bought by the user should reflect on _My Allocation_ without having to refresh the page
- [ ] Toast should appear correctly based on what the user's action performed.
- [ ] Transaction should not proceed if the user rejected it on MetaMask
- [ ] Remaining BUSD should tally with Remaining WZRD

**Comment by Emman1598** [comment]
Card


- [x] Check if the status is ongoing
- [x]  Check countdown timer if correct
- [x]  Check total raised if correct (total raised is the amount of WZRD token sold in BUSD)
- [ ]  Check if WZRD for sale if 500,000 WZRD ( to raise an issue)
- [x]  Check if buying coin is BUSD
- [x]  Check if distribution type is correct. (In Wizardia it is Vesting)

Individual Project Page

- [x]  Check status if ongoing
- [x]  Check social media links if correct
- [x]  Check countdown timer if correct
- [x]  Check percentage of tokens sold ( percentage = token sold / token for sale)
- [x]  Check total raised if correct (total raised is the amount of WZRD token sold in BUSD)
- [ ]  Check token price. ( 1 WZRD = 0.12 BUSD) (To raise an issue)
- [x]  Check tokens sold if correct
- [ ]  User should not be able to purchase more than their max allocation. (unable to test, only 20 WZRD tokens available)
- [x]  My allocation shows the number of tokens bought by the user
- [ ]  If users already bought all of their allocations, the purchase button should be disabled (unable to test, only 20 WZRD tokens available) 
- [x]  Sold Out button should appear if there are no more tokens available.

Purchase Modal

 
- [x] Check if Price per BUSD is correct
- [ ]  When clicking Max button, it should input the user's remaining allocation (To raise as an issue)
- [x]  My allocation shows the number of tokens bought by the user
- [x]  After swapping/buying, tokens bought by the user should reflect on My Allocation without having to refresh the page
- [x]  Toast should appear correctly based on what the user's action performed.
- [x]  Transaction should not proceed if the user rejected it on MetaMask
- [x]  Remaining BUSD should tally with Remaining WZRD


Issues to be raised:

- WZRD token for sale is not yet 500,000
![image](https://user-images.githubusercontent.com/100139337/157436176-53451228-1945-4c0c-9c36-38e08d94bf9a.png)

- Token price is not wrong
![Token price is wrong](https://user-images.githubusercontent.com/100139337/157436516-fe8f08b0-0875-4b80-9d5a-e36e263f8ec5.png)


- Clicking max button does not input users remaining allocation
![Does not input users remaining allocation when clicking max](https://user-images.githubusercontent.com/100139337/157436388-51617b45-f5dd-40dd-b238-fdca34ede536.png)
