### ISSUE TITLE
Ookeenga (OKG) IGO assets and details

### ISSUE THREAD

**Issue by swengr-janan** [mgguild/gamevault-frontend#204]
Ookeenga IGO Launch Information:
Preliminary Details:

- Token Name: Ookeenga
- Token Ticker: OKG
- Token Price: $0.04
- Buying Coin: BUSD
- Funds to be raised: USD 50,000
- Distribution Type: Vesting (5% up-front at TGE, 3month cliff, then quarterly vesting over 4 quarters)
- Contract Address: To follow

Project Details (Boilerplate for the card and page):

- Ookeenga (OKG) is a 3D NFT gaming project which combines blockchain technology with breath-taking graphics, appealing world-building, and addictive gameplay to create a uniquely immersive play-to-earn experience developed by CROS Gamestudio and published by SPORES Network.

- OKG is set in a world where insects have evolved and built a massive civilization in an ancient forest called Glaik (The Sacred Forest), which is divided into 2 factions: the Akhah (Pureblood) and the Ahika (Mixedblood).

Project links:

- Website: https://ookeenga.io/
- Twitter: https://twitter.com/ookeenga
- Telegram: https://t.me/ookeenga_global
- Youtube: https://www.youtube.com/channel/UCqQpViSkkAq_aFP3hj3GL8w

I. General Timeline
24 March 2022

- 1:00 PM UTC: Whitelisting/Snapshot

25 March 2022

- 1:00 PM UTC: Launchpad Sale starts (Round 1)

26 March 2022
1:00 PM UTC: Launchpad Sale ends

- 1:00 PM UTC: Start of Round 2 (FCFS Round)

Assets:
[assets.zip](https://github.com/mgguild/gamevault-frontend/files/8260925/assets.zip)

**Comment by swengr-janan** [comment]
to follow is assets, ginagawa pa

**Comment by kojiadrianojr** [comment]
Copy @swengr-janan on stand by
