### ISSUE TITLE
Adjust MGG launchpad background

### ISSUE THREAD

**Issue by Emman1598** [mgguild/gamevault-frontend#215]
This background should be in full screen when landing on launchpad.  The squared part should be the visible for the whole screen when landing on launchpad.

![image](https://user-images.githubusercontent.com/100139337/159230101-36f4df4a-7bbd-482f-a6a5-d3831c21f81d.png)

The red squared part should not be visible when landing on the launchpad page. 
![image](https://user-images.githubusercontent.com/100139337/159230226-2de9321c-a4a3-44cb-9972-3b4ac295235e.png)

Should look like this when landing on MGG launchpad page.
![image](https://user-images.githubusercontent.com/100139337/159230877-c3973075-c526-4bed-8306-791a8417515f.png)

**Comment by kojiadrianojr** [comment]
@swengr-janan diba naalala ko pinabawasan mo talaga yan?

**Comment by swengr-janan** [comment]
di tol, dapat full screen talaga yan, kung maaalala mo same sa SparkLaunch
