### ISSUE TITLE
Add claimable logo

### ISSUE THREAD

**Issue by Emman1598** [mgguild/gamevault-frontend#217]
Add claimable logo beside sold out, a green logo claimable should appear for participants and grey claimable logo for non participants. 

![Issue claimable](https://user-images.githubusercontent.com/100139337/159415107-dbf5d5fb-0096-4360-97b3-1b11d56ad1dc.png)

**Comment by kojiadrianojr** [comment]
Hello @Emman1598 refer natin to as indicator kasi misleading or magkakaroon ng misunderstanding if LOGO itatawag natin dito.
