### ISSUE TITLE
Claimable logo function

### ISSUE THREAD

**Issue by Emman1598** [mgguild/gamevault-frontend#221]
Claimable logo should turn green, if the user is a participant, and turn grey if user has already claimed his/her tokens, for non participants, it should also be grey. 

![Claimable issue](https://user-images.githubusercontent.com/100139337/159928722-868f118c-425a-4355-83b5-c6eceaf44879.png)

**Comment by kojiadrianojr** [comment]
dae na naman nagamit nang tama si component na tig gibo ko

**Comment by kojiadrianojr** [comment]
halat ta ifix ko daw
