### ISSUE TITLE
GameFi Vault UI Fix

### ISSUE THREAD

**Issue by Emman1598** [mgguild/gamevault-frontend#230]
- [x] Change 'hodl' to hold for LP and Pool based. 

![Issue 2](https://user-images.githubusercontent.com/100139337/160219503-211d43b1-d5a0-451c-8e8e-2d98c51c0376.png)

- [x] Change Background color from grey to a full screen respective color of the banner from LP and Pool Based. The black border from the banner should be moved below.

Darker blue:
![image](https://user-images.githubusercontent.com/100139337/160219932-f6df3ced-0777-44ac-8f5b-96082d92fb96.png)

Darker red:
![image](https://user-images.githubusercontent.com/100139337/160219953-d3016118-2054-4d60-a0d1-66c14d48fa91.png)

- [x] Change MGG logo position:

From here:
![Issue 3  p1](https://user-images.githubusercontent.com/100139337/160220353-977a4668-4d72-4d01-9054-39033c3883bd.png)

To Here:

![issue 1](https://user-images.githubusercontent.com/100139337/160220374-5043b6f1-624e-48c0-8fb7-d31d8431f965.png)

- [x] Change the home logo to a reset logo:

![Issue 4](https://user-images.githubusercontent.com/100139337/160220697-7d1681fa-b5ad-4e72-8b36-3416643c3465.png)

- [x] Remove Slide bar, (Slider bar should only appear if on mobile view):

![Issue 5](https://user-images.githubusercontent.com/100139337/160220832-74ceff6b-c713-43e3-98eb-2937b973c345.png)

**Comment by kojiadrianojr** [comment]
Sure ba yung 2nd task? parang ang pangit buong page color red or blue @Emman1598

**Comment by kojiadrianojr** [comment]
Wala man sakin yan na scroll bar @Emman1598

**Comment by kojiadrianojr** [comment]
Task done 2/5

**Comment by Emman1598** [comment]
@kojiadrianojr , dun sa background oo, medjo  plain kasi.  tapos ung parang pa fade na black the more u scroll down.  and for the scroll, chek ko ulet. naga appear kaya siya sako

**Comment by Emman1598** [comment]
@kojiadrianojr , medjo pa dark mo lang ung kulay ng red or blue.
