### ISSUE TITLE
Remove the encircled items

### ISSUE THREAD

**Issue by swengr-janan** [mgguild/gamevault-frontend#341]
<img width="692" alt="Screen Shot 2022-09-10 at 1 29 48 PM" src="https://user-images.githubusercontent.com/61826995/189470612-fbb4e643-b47b-4695-adbe-a0262f93b1f6.png">
<img width="817" alt="Screen Shot 2022-09-10 at 1 28 21 PM" src="https://user-images.githubusercontent.com/61826995/189470613-b4edd4fc-0839-4c52-a163-cbc731aaf609.png">

**Comment by kojiadrianojr** [comment]
Di ko sure if pwede halion yan @swengr-janan sa taas na screenshot ta pag ibang tokens, example mgg-busd, or something, mawawara itu

**Comment by swengr-janan** [comment]
ahh gets, pwede ba yan i dynamic? pag pool kaya 1 token lang

**Comment by kojiadrianojr** [comment]
staking-reward kasi ata yan, what if magkaiba si duwa? what ya think?

**Comment by swengr-janan** [comment]
sigs wait i explain ko nalang ki sir

**Comment by kojiadrianojr** [comment]
wait di ko pa sure eh, pa confirm ta nguna kay kuys @medardm
