### ISSUE TITLE
Individual project page ui improvements

### ISSUE THREAD

**Issue by swengr-janan** [mgguild/gamevault-frontend#58]
- [x] Move so med icon below Project title
- [x] Move ONGOING to the left
- [x] Apply equal margins for the text
![image](https://user-images.githubusercontent.com/61826995/153997258-d387e544-2793-4725-b82c-b429f4890470.png)

**Comment by Buko-pie** [comment]
PR for UI improvements https://github.com/mgguild/gamevault-frontend/pull/62
