### ISSUE TITLE
Add WBOND Equivalent in Price Per Box

### ISSUE THREAD

**Issue by swengr-janan** [mgguild/gamevault-frontend#71]
Price per Box = .30 BNB ( _LOGO_ 1,500 WBOND)

Add note na naka italicize 

current exchange rate on CMC

![image](https://user-images.githubusercontent.com/61826995/154411881-f20c9d8a-d663-47f3-a658-755dc1711a2c.png)

**Comment by kojiadrianojr** [comment]
Similar/connected issue with #73
