### ISSUE TITLE
Individual project page improvements

### ISSUE THREAD

**Issue by swengr-janan** [mgguild/gamevault-frontend#76]
- [x] Move Timer to the center
- [x] Enlarge font size of the timer
- [x] Move _ONGOING_ to the upper right corner

![image](https://user-images.githubusercontent.com/61826995/154310270-b2114c50-84b0-43fa-8135-2df5b012a320.png)

**Comment by Buko-pie** [comment]
resolved in PR: https://github.com/mgguild/gamevault-frontend/pull/90
